
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Regular Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002 "
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001B[H"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001B[F"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
blur = true

[window.padding]
x = 18
y = 18

[general]
live_config_reload = true
# Gruvbox-inspired Material terminal color scheme
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# Tokyo Night terminal color scheme
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
