---
- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Check if Oh My Zsh is installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: not oh_my_zsh_stat.stat.exists

- name: Symlink .zshrc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../../config/zsh/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes

- name: Symlink .zprofile
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../../config/zsh/.zprofile"
    dest: "{{ ansible_env.HOME }}/.zprofile"
    state: link
    force: yes
