lastupdatecheck: 0
recentrepos:
    - /Volumes/LCS.Data/C-Projects
    - /Users/lcs-dev/Dotfiles
    - /Users/lcs-dev/LCS.Data/ING-S/Prog-Scacchi_Knuth
    - /Volumes/LCS.Data/ING-S/Prog-Scacchi_Knuth
    - /Users/lcs-dev/LCS.Data/Dev-Projects
    - /Volumes/LCS.Data/Dev-Projects
    - /Volumes/LCS.Data/Blog
startuppopupversion: 5
lastversion: 0.53.0
customcommandshistory:
    - q
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
